version: '3'

services:
  fastify:
    build: .
    container_name: fastify
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    environment:
      - PORT=${PORT:-8000}
      - NODE_ENV=${NODE_ENV:-production}
      - DEBUG
